/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.example.ui;

/**
 *
 * @author PC-LORENZO
 */
public class PlayerViewUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form PlayerViewUI
     */
    public PlayerViewUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        logPanel = new javax.swing.JPanel();
        tPointsLabel = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        tPointsCbox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        searchB = new javax.swing.JButton();
        logBg = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logPanel.setBackground(new java.awt.Color(27, 27, 27));
        logPanel.setPreferredSize(new java.awt.Dimension(550, 400));
        logPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tPointsLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\tournamentPoints.png")); // NOI18N
        logPanel.add(tPointsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 510, 80));

        userField.setBackground(new java.awt.Color(0, 0, 0));
        userField.setFont(new java.awt.Font("Lora", 1, 14)); // NOI18N
        userField.setForeground(new java.awt.Color(255, 157, 0));
        userField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        logPanel.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 260, 50));

        userLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\user.png")); // NOI18N
        logPanel.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 370, 80));

        tPointsCbox.setBackground(new java.awt.Color(0, 0, 0));
        tPointsCbox.setForeground(new java.awt.Color(255, 157, 0));
        tPointsCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tPointsCbox.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        logPanel.add(tPointsCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 330, 50));

        jTable2.setBackground(new java.awt.Color(0, 0, 0));
        jTable2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        jTable2.setForeground(new java.awt.Color(255, 157, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        logPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 277, 960, 390));

        searchB.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\creationUI\\search.png")); // NOI18N
        searchB.setContentAreaFilled(false);
        logPanel.add(searchB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 210, 80, 70));

        logBg.setBackground(new java.awt.Color(0, 0, 0));
        logBg.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\logPanel.jpg")); // NOI18N
        logBg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(6, 27, 42), new java.awt.Color(6, 27, 42), new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51)));
        logPanel.add(logBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 700));

        mainPanel.add(logPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 100, 1250, 700));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\bg.jpg")); // NOI18N
        mainPanel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 960));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel logBg;
    private javax.swing.JPanel logPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton searchB;
    private javax.swing.JComboBox<String> tPointsCbox;
    private javax.swing.JLabel tPointsLabel;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
