/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.example.ui;

import org.example.data.Players;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author PC-LORENZO
 */
public class PlayerProfile extends javax.swing.JInternalFrame {

    Players player;
    /**
     * Creates new form PlayerProfile
     */
    public PlayerProfile(Players player) {
        this.player = player;
        initComponents();
        username.setText(player.getPlayer_name());
        tpoints.setText(String.valueOf(player.getTournament_points()));
        jTextArea1.setText(player.getPlayer_description());
        // Eliminar el borde decorativo
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        ui.setEastPane(null);
        ui.setWestPane(null);
        ui.setSouthPane(null);
        this.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        logPanel = new javax.swing.JPanel();
        tPointsLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        tpoints = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        logBg = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logPanel.setBackground(new java.awt.Color(27, 27, 27));
        logPanel.setPreferredSize(new java.awt.Dimension(550, 400));
        logPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tPointsLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\tournamentPoints.png")); // NOI18N
        logPanel.add(tPointsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 510, 80));

        userLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\user.png")); // NOI18N
        logPanel.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 370, 80));

        tpoints.setFont(new java.awt.Font("Lora", 1, 36)); // NOI18N
        tpoints.setForeground(new java.awt.Color(255, 157, 0));
        tpoints.setText("LONOAL02");
        logPanel.add(tpoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 350, 80));

        descriptionLabel.setFont(new java.awt.Font("Lora", 1, 36)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 157, 0));
        descriptionLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\description.png")); // NOI18N
        logPanel.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 380, 80));

        username.setFont(new java.awt.Font("Lora", 1, 36)); // NOI18N
        username.setForeground(new java.awt.Color(255, 157, 0));
        username.setText("LONOAL02");
        logPanel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 350, 80));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lora", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 157, 0));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        logPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 550, 210));

        logBg.setBackground(new java.awt.Color(0, 0, 0));
        logBg.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\logPanel.jpg")); // NOI18N
        logBg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(6, 27, 42), new java.awt.Color(6, 27, 42), new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51)));
        logPanel.add(logBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 630));

        mainPanel.add(logPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 1120, 630));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\bg.jpg")); // NOI18N
        mainPanel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 960));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logBg;
    private javax.swing.JPanel logPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel tPointsLabel;
    private javax.swing.JLabel tpoints;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
