/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.example.ui;

/**
 *
 * @author PC-LORENZO
 */
public class TournamentCreationUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form TournamentCreationUI
     */
    public TournamentCreationUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        logPanel = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        signButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTField = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        logBg = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logPanel.setBackground(new java.awt.Color(27, 27, 27));
        logPanel.setPreferredSize(new java.awt.Dimension(550, 400));
        logPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descriptionLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\description.png")); // NOI18N
        logPanel.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 130, 400, 80));

        userField.setBackground(new java.awt.Color(0, 0, 0));
        userField.setFont(new java.awt.Font("Lora", 1, 14)); // NOI18N
        userField.setForeground(new java.awt.Color(255, 157, 0));
        userField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        logPanel.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 250, 40));

        userLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\name.png")); // NOI18N
        logPanel.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 80));

        signButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\button_create.png")); // NOI18N
        signButton.setBorderPainted(false);
        signButton.setContentAreaFilled(false);
        signButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonActionPerformed(evt);
            }
        });
        logPanel.add(signButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 740, 210, 80));

        descriptionTField.setBackground(new java.awt.Color(0, 0, 0));
        descriptionTField.setColumns(20);
        descriptionTField.setFont(new java.awt.Font("Lora", 1, 14)); // NOI18N
        descriptionTField.setForeground(new java.awt.Color(255, 157, 0));
        descriptionTField.setRows(5);
        descriptionTField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        jScrollPane1.setViewportView(descriptionTField);

        logPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 210, 410, 320));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setForeground(new java.awt.Color(255, 157, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        logPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 330, 50));

        jComboBox2.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox2.setForeground(new java.awt.Color(255, 157, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        logPanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 330, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\game.png")); // NOI18N
        logPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 250, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\gStage.png")); // NOI18N
        logPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 410, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\nOfTeams.png")); // NOI18N
        logPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 400, 60));
        logPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 220, 60));
        logPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 220, 60));
        logPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 220, 60));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jCheckBox1.setToolTipText("");
        jCheckBox1.setBorder(null);
        jCheckBox1.setPreferredSize(new java.awt.Dimension(90, 90));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        logPanel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 20, 30));

        logBg.setBackground(new java.awt.Color(0, 0, 0));
        logBg.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\logPanelXl.jpg")); // NOI18N
        logBg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(6, 27, 42), new java.awt.Color(6, 27, 42), new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51)));
        logPanel.add(logBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 870));

        mainPanel.add(logPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 50, 1800, 870));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\bg.jpg")); // NOI18N
        mainPanel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 960));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signButtonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTField;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logBg;
    private javax.swing.JPanel logPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton signButton;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
