/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.example.ui;

import javax.swing.*;
import java.util.Objects;

/**
 *
 * @author PC-LORENZO
 */
public class TournamentCreationUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form TournamentCreationUI
     */
    public TournamentCreationUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        logPanel = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        signButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTField = new javax.swing.JTextArea();
        tpointCbox = new javax.swing.JComboBox<>();
        gstagesizeCbox = new javax.swing.JComboBox<>();
        nteamsCbox = new javax.swing.JComboBox<>();
        gameCbox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        looserbB = new javax.swing.JButton();
        gstageB = new javax.swing.JButton();
        logBg = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logPanel.setBackground(new java.awt.Color(27, 27, 27));
        logPanel.setPreferredSize(new java.awt.Dimension(550, 400));
        logPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descriptionLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\description.png")); // NOI18N
        logPanel.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 110, 400, 80));

        userField.setBackground(new java.awt.Color(0, 0, 0));
        userField.setFont(new java.awt.Font("Lora", 1, 14)); // NOI18N
        userField.setForeground(new java.awt.Color(255, 157, 0));
        userField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        logPanel.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 250, 40));

        userLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\name.png")); // NOI18N
        logPanel.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 80));

        signButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\button_create.png")); // NOI18N
        signButton.setBorderPainted(false);
        signButton.setContentAreaFilled(false);
        signButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonActionPerformed(evt);
            }
        });
        logPanel.add(signButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 740, 210, 80));

        descriptionTField.setBackground(new java.awt.Color(0, 0, 0));
        descriptionTField.setColumns(20);
        descriptionTField.setFont(new java.awt.Font("Lora", 1, 14)); // NOI18N
        descriptionTField.setForeground(new java.awt.Color(255, 157, 0));
        descriptionTField.setRows(5);
        descriptionTField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        jScrollPane1.setViewportView(descriptionTField);

        logPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 200, 570, 410));

        tpointCbox.setBackground(new java.awt.Color(0, 0, 0));
        tpointCbox.setForeground(new java.awt.Color(255, 157, 0));
        tpointCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tpointCbox.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        logPanel.add(tpointCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 330, 50));

        gstagesizeCbox.setBackground(new java.awt.Color(0, 0, 0));
        gstagesizeCbox.setForeground(new java.awt.Color(255, 157, 0));
        gstagesizeCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gstagesizeCbox.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        logPanel.add(gstagesizeCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 330, 50));

        nteamsCbox.setBackground(new java.awt.Color(0, 0, 0));
        nteamsCbox.setForeground(new java.awt.Color(255, 157, 0));
        nteamsCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nteamsCbox.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        logPanel.add(nteamsCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 330, 50));

        gameCbox.setBackground(new java.awt.Color(0, 0, 0));
        gameCbox.setForeground(new java.awt.Color(255, 157, 0));
        gameCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gameCbox.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 157, 0), new java.awt.Color(255, 157, 0)));
        logPanel.add(gameCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 330, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\looserBracket.png")); // NOI18N
        logPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 460, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\tpointsRequired.png")); // NOI18N
        logPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 570, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\gStageSize.png")); // NOI18N
        logPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 480, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\game.png")); // NOI18N
        logPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 250, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\gStage.png")); // NOI18N
        logPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 410, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\nOfTeams.png")); // NOI18N
        logPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 400, 60));

        looserbB.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\creationUI\\emptyCbox.png")); // NOI18N
        looserbB.setBorderPainted(false);
        looserbB.setContentAreaFilled(false);
        looserbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                looserbBActionPerformed(evt);
            }
        });
        logPanel.add(looserbB, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 550, 70, 70));

        gstageB.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\creationUI\\emptyCbox.png")); // NOI18N
        gstageB.setBorderPainted(false);
        gstageB.setContentAreaFilled(false);
        gstageB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstageBActionPerformed(evt);
            }
        });
        logPanel.add(gstageB, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 70, 70));

        logBg.setBackground(new java.awt.Color(0, 0, 0));
        logBg.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\logPanelXl.jpg")); // NOI18N
        logBg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(6, 27, 42), new java.awt.Color(6, 27, 42), new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 51)));
        logPanel.add(logBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 870));

        mainPanel.add(logPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 50, 1800, 870));

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC-LORENZO\\Documents\\NetBeansProjects\\ChampionForge\\src\\icons\\login\\bg.jpg")); // NOI18N
        mainPanel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 960));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signButtonActionPerformed

    private void looserbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_looserbBActionPerformed
        // TODO add your handling code here:
        String checked = "src/icons/creationUI/cbox.png";
        String empty = "src/icons/creationUI/emptyCbox.png";
        if (looserbB.getIcon().toString().equals(checked)) {
            looserbB.setIcon(new ImageIcon(empty));
        }else {
            looserbB.setIcon(new ImageIcon(checked));
        }

    }//GEN-LAST:event_looserbBActionPerformed

    private void gstageBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstageBActionPerformed
        // TODO add your handling code here:
        String checked = "src/icons/creationUI/cbox.png";
        String empty = "src/icons/creationUI/emptyCbox.png";
        if (gstageB.getIcon().toString().equals(checked)) {
            gstageB.setIcon(new ImageIcon(empty));
        }else {
            gstageB.setIcon(new ImageIcon(checked));
        }
    }//GEN-LAST:event_gstageBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTField;
    private javax.swing.JComboBox<String> gameCbox;
    private javax.swing.JButton gstageB;
    private javax.swing.JComboBox<String> gstagesizeCbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logBg;
    private javax.swing.JPanel logPanel;
    private javax.swing.JButton looserbB;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> nteamsCbox;
    private javax.swing.JButton signButton;
    private javax.swing.JComboBox<String> tpointCbox;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
